apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: savitha1/flask-k8s-storage:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: flask-data
          mountPath: /data  # Mount the PVC at /data
      volumes:
      - name: flask-data
        persistentVolumeClaim:
          claimName: flask-pvc  # PVC we created earlier
